context:
  name: Maartens_Resource_Compiler
  version: "1.3.16"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/mhekkel/mrc/archive/refs/tags/v${{ version }}.tar.gz
  sha256: f69fac01e04d988699a9a0e36f4f71e7bbb06a5185753300b1ff627cad09799f

build:
  number: 0
  skip:
    - osx
  script:
    - if: unix
      then: |
        set -exo pipefail
        cmake -S . -B build ${CMAKE_ARGS} -DBUILD_TESTING=ON
        cmake --build build --config Release --parallel ${CPU_COUNT}
        ctest -V -C Release --test-dir build
        cmake --install build
      else: |
        @echo on
        cmake -S . -B build %CMAKE_ARGS% -DBUILD_TESTING=ON
        if errorlevel 1 exit 1
        cmake --build build --config Release --parallel %CPU_COUNT%
        if errorlevel 1 exit 1
        ctest -V -C Release --test-dir build
        if errorlevel 1 exit 1
        cmake --install build
        if errorlevel 1 exit 1

requirements:
  build:
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - cmake
    - if: unix
      then: make
    - pkg-config
  host:
    - catch2
    - libmcfp

tests:
  - script:
      - mrc --version
      - mrc --header -o mrsrc.h

about:
  homepage: https://github.com/mhekkel/mrc
  repository: https://github.com/mhekkel/mrc
  documentation: https://github.com/mhekkel/mrc/blob/v${{ version }}/README.md
  license: BSD-2-Clause
  license_file: LICENSE
  summary: "mrc - Maartens Resource Compiler"
  description: >
    MRC is a tool for parsing and compiling resource files.
    It provides functionality to handle various resource formats and compile them into binary resources for use in applications.

extra:
  recipe-maintainers:
    - eunos-1128
